# Generated by Django 5.0.6 on 2025-02-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('succeeded', 'Проведена'), ('failed', 'Отклонена')], default='draft', max_length=30, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'закупка',
                'ordering': ('status',),
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.inventory', verbose_name='инвентарь')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.shipment', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
                'unique_together': {('inventory', 'count')},
            },
        ),
    ]
