# Generated by Django 5.0.6 on 2025-02-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_repair_repairitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('active', 'Выдано'), ('cancel', 'Отклонено')], default='created', max_length=30, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('start_date', models.DateTimeField(editable=False, verbose_name='дата выдачи')),
                ('end_date', models.DateField(verbose_name='дата возврата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'выдача инвентаря',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.inventory', verbose_name='инвентарь')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'инвентарь',
                'verbose_name_plural': 'позиции',
                'unique_together': {('order', 'inventory')},
            },
        ),
    ]
