# Generated by Django 5.0.6 on 2025-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='дата выдачи'),
        ),
    ]
