# Generated by Django 5.0.6 on 2025-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('active', 'Выдано'), ('returned', 'Возвращено'), ('cancel', 'Отклонено')], default='created', max_length=30, verbose_name='статус'),
        ),
    ]
