# Generated by Django 5.0.6 on 2025-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vendor',
            field=models.CharField(default='', max_length=255, verbose_name='поставщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'План'), ('succeeded', 'Проведена'), ('failed', 'Отклонена')], default='draft', max_length=30, verbose_name='статус'),
        ),
    ]
