# Generated by Django 5.0.6 on 2025-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_shipment_vendor_shipmentitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
