# Generated by Django 5.0.6 on 2025-02-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status', '-created_at'), 'verbose_name': 'заявку', 'verbose_name_plural': 'выдача инвентаря'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='slug',
        ),
    ]
